# Generated by Django 5.2.8 on 2025-11-13 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'comment', 'verbose_name_plural': 'comment list'},
        ),
    ]
