# Generated by Django 5.2.8 on 2025-11-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totododo', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d', verbose_name='이미지'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
