# Generated by Django 5.2.8 on 2025-11-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totododo', '0005_todo_image_todo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='todo/%Y/%m/%d', verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='todo/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
